version: 2.1.{build}
install: 
    - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: 'src\SharedAssemblyVersion.cs'
  assembly_version: '$(appveyor_build_version)'
  assembly_file_version: '$(appveyor_build_version)'
nuget:
  account_feed: true
before_build:
- cmd: nuget restore
- ps: Vsix-IncrementVsixVersion
build:
  project: Sitecore.Rocks.sln
  verbosity: minimal
after_build:
- ps: >-
    msbuild .\src\Sitecore.Rocks.Server\Sitecore.Rocks.Server.csproj /p:Configuration=Release /p:Platform=AnyCPU /p:DeployOnBuild=true /p:PublishProfile=FilesystemPublish /p:DebugType=None /verbosity:minimal

    Install-Module -Name Sitecore.Courier

    New-CourierPackage -Target "$((pwd).Path)\src\Sitecore.Rocks.Server\bin\Release\Publish" -Output "$((pwd).Path)\src\Sitecore.Rocks.Server\bin\Sitecore.Rocks.Server.update" -IncludeFiles $true -SerializationProvider "Sitecore"
artifacts:
- path: src\Sitecore.Rocks.VisualStudio\bin\Release\Sitecore.Rocks.VisualStudio.vsix
  name: Sitecore.Rocks.VisualStudio.vsix
- path: src\Sitecore.Rocks.Server\bin\Sitecore.Rocks.Server.update
  name: Sitecore.Rocks.Server.update
