// © 2015-2016 Sitecore Corporation A/S. All rights reserved.

using System.IO;
using EnvDTE80;
using Sitecore.Rocks.Annotations;
using Sitecore.Rocks.CodeGeneration.CodeFirstTemplates.Templates;
using Sitecore.Rocks.Diagnostics;
using Sitecore.Rocks.Extensibility.Pipelines;

namespace Sitecore.Rocks.CodeGeneration.CodeFirstTemplates.Pipelines.ProcessCodeFirstTemplates
{
    [Pipeline(typeof(ProcessCodeFirstTemplatesPipeline), 7000)]
    public class GenerateCode : PipelineProcessor<ProcessCodeFirstTemplatesPipeline>
    {
        protected override void Process(ProcessCodeFirstTemplatesPipeline pipeline)
        {
            Debug.ArgumentNotNull(pipeline, nameof(pipeline));

            var output = new StringWriter();
            var ns = string.Empty;

            foreach (var template in pipeline.Templates)
            {
                var codeClass = template.CodeElement as CodeClass2;
                if (codeClass == null)
                {
                    continue;
                }

                ns = codeClass.Namespace.FullName;
                WriteTemplate(output, template, codeClass);
            }

            var o = output.ToString();
            if (string.IsNullOrEmpty(o))
            {
                return;
            }

            var result = new StringWriter();

            const string Text = @"      
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace {0}
{{


  using System;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;

{1}


}}";

            result.WriteLine(string.Format(Text, ns, o));

            pipeline.DesignerFile = result.ToString();
        }

        private void WriteTemplate([NotNull] StringWriter output, [NotNull] Template template, [NotNull] CodeClass2 codeClass)
        {
            Debug.ArgumentNotNull(output, nameof(output));
            Debug.ArgumentNotNull(template, nameof(template));
            Debug.ArgumentNotNull(codeClass, nameof(codeClass));

            if (codeClass.ClassKind != vsCMClassKind.vsCMClassKindPartialClass)
            {
                return;
            }

            output.WriteLine(string.Format("  public partial class {0}", codeClass.Name));
            output.WriteLine("  {");

            output.WriteLine("    public static class Template");
            output.WriteLine("    {");
            output.WriteLine(string.Format("      public static readonly Guid TemplateId = new Guid(\"{0}\");", template.TemplateItemId));
            output.WriteLine("      public static class Fields");
            output.WriteLine("      {");

            foreach (var templateSection in template.Sections)
            {
                foreach (var templateField in templateSection.Fields)
                {
                    output.WriteLine(string.Format("        public static readonly Guid {0} = new Guid(\"{1}\");", templateField.Property.Name, templateField.TemplateFieldItemId));
                }
            }

            output.WriteLine("      }");

            output.WriteLine("    }");
            output.WriteLine("  }");
            output.WriteLine("#pragma warning restore 1591");
        }
    }
}
