//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sitecore.Rocks.Annotations;
using Sitecore.Rocks.Data;

#pragma warning disable 1591

namespace Sitecore.Rocks.Shell.Environment
{
  using Rocks.Annotations;
  using Rocks.Data;
  using Rocks.Sites;



  public partial class ServerHost 
  {
    public partial class PublishingRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void AdvancedPublish72([NotNull] ItemUri itemUri, [NotNull] string mode, [NotNull] string source, [NotNull] string languages, [NotNull] string targets, [NotNull] string relatedItems, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("Publishing.AdvancedPublish72", completed, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString(), mode, source, languages, targets, relatedItems);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void PublishItemAndRelatedItems([NotNull] DatabaseUri databaseUri, [NotNull] string itemsList, [NotNull] string deep, [NotNull] string compareRevisions, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("Publishing.PublishItemAndRelatedItems", completed, databaseUri.DatabaseName.ToString(), itemsList, deep, compareRevisions);
      }

    }

    public partial class RulesRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetConditionsAndActions71([NotNull] DatabaseUri databaseUri, [NotNull] string dataSource, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("Rules.GetConditionsAndActions71", completed, databaseUri.DatabaseName.ToString(), dataSource);
      }

    }

  }


}

#pragma warning restore 1591
