//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sitecore.Rocks.Annotations;
using Sitecore.Rocks.Data;

#pragma warning disable 1591

namespace Sitecore.Rocks.Shell.Environment
{
  using Rocks.Annotations;
  using Rocks.Data;
  using Rocks.Sites;



  public partial class ServerHost 
  {
    private FormsRequests formsrequests;

    [NotNull]
    public FormsRequests Forms { get { return this.formsrequests ?? (this.formsrequests = new FormsRequests()); }}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public partial class FormsRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetFormRenderings([NotNull] DatabaseUri databaseUri, [NotNull] string itemIdOrPath, [NotNull] string fields, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("Forms.GetFormRenderings", completed, databaseUri.DatabaseName.ToString(), itemIdOrPath, fields);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void SaveForm([NotNull] ItemUri itemUri, [NotNull] string form, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("Forms.SaveForm", completed, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString(), form);
      }

    }

  }


}

#pragma warning restore 1591
