//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sitecore.Rocks.Annotations;
using Sitecore.Rocks.Data;
using Sitecore.Rocks.Sites;

#pragma warning disable 1591

namespace Sitecore.Rocks.Shell.Environment
{
  using Rocks.Annotations;
  using Rocks.Data;
  using Rocks.Sites;



  public partial class ServerHost 
  {
    private ValidationsRequests validationsrequests;

    [NotNull]
    public ValidationsRequests Validations { get { return this.validationsrequests ?? (this.validationsrequests = new ValidationsRequests()); }}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public partial class ValidationsRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetItemValidation([NotNull] string contextName, [NotNull] ItemUri itemUri, [NotNull] string languageName, [NotNull] string version, [NotNull] string deep, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("Validations.GetItemValidation", completed, contextName, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString(), languageName, version, deep);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void StartItemValidation([NotNull] string contextName, [NotNull] ItemUri itemUri, [NotNull] string languageName, [NotNull] string version, [NotNull] string inactiveValidations, [NotNull] string customValidations, [NotNull] string deep, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("Validations.StartItemValidation", completed, contextName, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString(), languageName, version, inactiveValidations, customValidations, deep);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetValidationReport([NotNull] Site site, [NotNull] string contextName, [NotNull] ExecuteCompleted completed)
      {
        site.DataService.ExecuteAsync("Validations.GetValidationReport", completed, contextName);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetValidations([NotNull] Site site, [NotNull] string contextName, [NotNull] ExecuteCompleted completed)
      {
        site.DataService.ExecuteAsync("Validations.GetValidations", completed, contextName);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void StartValidationAssessment([NotNull] Site site, [NotNull] string contextName, [NotNull] string databasesAndLanguages, [NotNull] string inactiveValidations, [NotNull] string customValidations, [NotNull] ExecuteCompleted completed)
      {
        site.DataService.ExecuteAsync("Validations.StartValidationAssessment", completed, contextName, databasesAndLanguages, inactiveValidations, customValidations);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void TestQuery([NotNull] DatabaseUri databaseUri, [NotNull] string query, [NotNull] string checkType, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("Validations.TestQuery", completed, databaseUri.DatabaseName.ToString(), query, checkType);
      }

    }

  }


}

#pragma warning restore 1591
