//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sitecore.Rocks.Annotations;
using Sitecore.Rocks.Data;

#pragma warning disable 1591

namespace Sitecore.Rocks.Shell.Environment
{
  using Rocks.Annotations;
  using Rocks.Data;
  using Rocks.Sites;



  public partial class ServerHost 
  {
    private DocumentationRequests documentationrequests;

    [NotNull]
    public DocumentationRequests Documentation { get { return this.documentationrequests ?? (this.documentationrequests = new DocumentationRequests()); }}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public partial class DocumentationRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void Import([NotNull] DatabaseUri databaseUri, [NotNull] string xml, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("Documentation.Import", completed, databaseUri.DatabaseName.ToString(), xml);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void Export([NotNull] ItemUri itemUri, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("Documentation.Export", completed, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString());
      }

    }

    private LayoutBuildersRequests layoutbuildersrequests;

    [NotNull]
    public LayoutBuildersRequests LayoutBuilders { get { return this.layoutbuildersrequests ?? (this.layoutbuildersrequests = new LayoutBuildersRequests()); }}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public partial class LayoutBuildersRequests
    {
      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void CreateDataSource([NotNull] ItemUri itemUri, [NotNull] string name, [NotNull] string location, [NotNull] string templateId, [NotNull] ExecuteCompleted completed)
      {
        itemUri.Site.DataService.ExecuteAsync("LayoutBuilders.CreateDataSource", completed, itemUri.DatabaseUri.DatabaseName.ToString(), itemUri.ItemId.ToString(), name, location, templateId);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetPlaceHolderSettings([NotNull] DatabaseUri databaseUri, [NotNull] string placeHolderName, [NotNull] string placeHolderPath, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("LayoutBuilders.GetPlaceHolderSettings", completed, databaseUri.DatabaseName.ToString(), placeHolderName, placeHolderPath);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetQuickSteps([NotNull] DatabaseUri databaseUri, [NotNull] string layout, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("LayoutBuilders.GetQuickSteps", completed, databaseUri.DatabaseName.ToString(), layout);
      }

      [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
      public void GetRenderingsInPlaceHolder([NotNull] DatabaseUri databaseUri, [NotNull] string placeHolderName, [NotNull] string placeHolderPath, [NotNull] ExecuteCompleted completed)
      {
        databaseUri.Site.DataService.ExecuteAsync("LayoutBuilders.GetRenderingsInPlaceHolder", completed, databaseUri.DatabaseName.ToString(), placeHolderName, placeHolderPath);
      }

    }

  }


}

#pragma warning restore 1591
